config/routes.rb
Testing::Application.routes.draw do

  devise_for :users

  root :to => 'groups#index'
  resources :groups

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :description, :user_id, :question_id

  belongs_to :question, :counter_cache => true
  belongs_to :user

end

app/models/group.rb
class Group < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :name

  has_many :questions

end

app/models/question.rb
class Question < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :question, :description, :group_id

  belongs_to :group
  has_many :answers
  has_many :users, :thoungh => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :first_name, :last_name, :email

  #validates
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new

  end

  def all_comm
    @comments = Comment.paginate(:page => params[:page], :per_page => 5).order("created_at ASC").all
    #@comments = Comment.order("created_at ASC").all
  end

  def create
    comment = current_user.comments.new(params[:comment])
    comment.save!
    redirect_to :back
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.all
  end

  def all_img
    @pictures = Picture.paginate(:page => params[:page], :per_page => 21).order("likes_count DESC")
  end

  def show
    @question = Question.includes(:comments).find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.haml
%h1 Listing groups

- @groups.each do |group|
  |
  = link_to group.name, group_path(:id => group.id)#, :class => "category", "data-id" => group.id

-#.i_modal_window{:style => "display: none;"}
-#  %div
-#    %p
-#    = image_tag "#", :id => "rand_pict"

.clear

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path


%h1 #{@group.name}
= will_paginate @pictures
- @question.each do |quest|
  %div{:style => "float:left; width: 130px; height: 150px; padding: 10px; text-align: center; font-size: 12px"}
    = "Question: #{quest.questions.count.to_i} "
    %br
    = "Answer: #{quest.answers_count.to_i}"
    = link_to question_path(:id => question.id) do
      = image_tag img.image.with_border.url
.clear

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Testing"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Testing

          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
          .nav-collapse
            .pull-right
              - if user_signed_in?
                Signed in as
                %strong
                  #{current_user.email}
                = link_to "Sign out", destroy_user_session_path, :method => :delete
              - else
                = link_to "Sign up", new_user_registration_path
                or #{link_to "sign in", new_user_session_path}

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            -#%h3 Users
              -#%ul.nav.nav-list
                %li.nav-header Sidebar
                - if user_signed_in?
                  %li= link_to "ruby"#, "/catlist?id=1"
                  %li= link_to "christmas"#, "/catlist?id=2"
            -#%h3 Sidebar
            -#%ul.nav.nav-list
            -#  %li.nav-header Sidebar
            -#  %li= link_to "Link 1", "/path1"
            -#  %li= link_to "Link 2", "/path2"
            -#  %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/questions/show.html.haml
-#%div{:style => "text-align: center "}
-#  = link_to image_tag(@picture.image.url) #, :onclick => "sendTracking(this, '#{current_user.id}');"
-#  %br
-#  = link_to "Like: #{@picture.likes_count.to_i}", like_path(@picture.id), :class => "button"
-#%p= "Comments: #{@picture.comments.count.to_i}"
-#- @picture.comments.each do |comment|
-#  .well
-#    %code #{comment.user.email} said:
-#    = comment.body
-#= form_for :comment, :url => comments_path do |f|
-#  = f.text_area :body
-#  = f.hidden_field :picture_id, :value => @picture.id
-#  %br
-#  = f.submit :value => "save"